import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAuth } from "@/lib/apiAuth";
import {
  generateTitle,
  generateSKU,
  generateSEOTitle,
  generateSEODescription,
  generatePageUrl,
  generateTags,
  generateHTMLDescription,
  calculateDiscountedPrice,
} from "@/lib/autoGenerate";
import { createProduct } from "@/lib/shopify";
import { logActivity } from "@/lib/activityLog";

interface VariantInput {
  colorCode: string;
  colorName?: string;
  frameColor?: string;
  templeColor?: string;
  frameSize?: string;
  bridge?: string;
  templeLength?: string;
  weight?: string;
  lensColour?: string;
  tint?: string;
  mrp?: number;
  barcode?: string;
  locations?: Array<{ locationId: string; quantity: number }>;
}

export async function GET(request: NextRequest) {
  try {
    const auth = await requireAuth();
    if (!auth.authorized) return auth.response!;
    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "10");
    const category = searchParams.get("category");
    const brand = searchParams.get("brand");
    const status = searchParams.get("status");
    const location = searchParams.get("location");
    const search = searchParams.get("search");
    const shape = searchParams.get("shape");
    const frameMaterial = searchParams.get("frameMaterial");
    const gender = searchParams.get("gender");

    const skip = (page - 1) * limit;

    const where: Record<string, unknown> = {};
    if (category) where.category = category;
    if (brand) where.brand = { equals: brand, mode: "insensitive" };
    if (status) where.status = status;
    if (shape) where.shape = { equals: shape, mode: "insensitive" };
    if (frameMaterial) where.frameMaterial = { equals: frameMaterial, mode: "insensitive" };
    if (gender) where.gender = { equals: gender, mode: "insensitive" };
    if (search) {
      where.OR = [
        { title: { contains: search, mode: "insensitive" } },
        { brand: { contains: search, mode: "insensitive" } },
        { productName: { contains: search, mode: "insensitive" } },
      ];
    }

    const [products, total] = await Promise.all([
      prisma.product.findMany({
        where,
        skip,
        take: limit,
        include: {
          images: true,
          locations: true,
          syncLogs: true,
        },
        orderBy: { createdAt: "desc" },
      }),
      prisma.product.count({ where }),
    ]);

    const filteredProducts = location
      ? products.filter((p) =>
          p.locations.some((l) => l.locationId === location)
        )
      : products;

    return NextResponse.json(
      {
        success: true,
        data: filteredProducts,
        pagination: {
          page,
          limit,
          total,
          pages: Math.ceil(total / limit),
        },
      },
      { status: 200 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}

interface CreateProductRequest {
  [key: string]: any;
  brand: string;
  category: string;
  mrp: number;
  images?: Array<Record<string, any>>;
  locations?: Array<{ locationId: string; quantity: number }>;
  variants?: VariantInput[];
}

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuth(["ADMIN", "CATALOG_MANAGER"]);
    if (!auth.authorized) return auth.response!;

    const body: CreateProductRequest = await request.json();

    const discountRules = await prisma.discountRule.findMany();

    const autoGeneratedData = {
      title: body.title || generateTitle(body),
      sku: generateSKU(body),
      seoTitle: generateSEOTitle(body),
      seoDescription: generateSEODescription(body),
      pageUrl: generatePageUrl(body),
      tags: generateTags(body),
      htmlDescription: generateHTMLDescription(body),
      discountedPrice: calculateDiscountedPrice(
        body.mrp,
        body.category,
        discountRules
      ),
    };

    const product = await prisma.product.create({
      data: {
        title: autoGeneratedData.title,
        sku: autoGeneratedData.sku,
        brand: body.brand,
        subBrand: body.subBrand,
        fullModelNo: body.fullModelNo,
        frameSize: body.frameSize,
        frameColor: body.frameColor,
        productName: body.productName,
        category: body.category,
        modelNo: body.modelNo,
        colorCode: body.colorCode,
        shape: body.shape,
        frameMaterial: body.frameMaterial,
        frameType: body.frameType,
        gender: body.gender,
        templeColor: body.templeColor,
        templeMaterial: body.templeMaterial,
        weight: body.weight,
        bridge: body.bridge || body.bridgeWidth,
        templeLength: body.templeLength,
        gtin: body.gtin,
        upc: body.upc,
        lensMaterial: body.lensMaterial,
        lensColour: body.lensColour,
        tint: body.tint,
        lensUSP: body.lensUSP,
        polarization: body.polarization,
        uvProtection: body.uvProtection,
        productUSP: body.productUSP,
        countryOfOrigin: body.countryOfOrigin,
        warranty: body.warranty,
        label: body.label,
        recommendedFor: body.recommendedFor,
        instructions: body.instructions,
        ingredients: body.ingredients,
        benefits: body.benefits,
        aboutProduct: body.aboutProduct,
        mrp: body.mrp || 0,
        discountedPrice: autoGeneratedData.discountedPrice,
        compareAtPrice: body.mrp || 0,
        seoTitle: autoGeneratedData.seoTitle,
        seoDescription: autoGeneratedData.seoDescription,
        pageUrl: autoGeneratedData.pageUrl,
        tags: autoGeneratedData.tags,
        htmlDescription: autoGeneratedData.htmlDescription,
        status: body.status || "DRAFT",
        images: {
          create: body.images?.map((img: any) => ({
            url: img.url,
            originalUrl: img.originalUrl || img.url,
          })) || [],
        },
        locations: {
          create: body.locations?.map((loc) => ({
            locationId: loc.locationId,
            quantity: loc.quantity,
          })) || [],
        },
      },
      include: {
        images: true,
        locations: true,
        syncLogs: true,
      },
    });

    // ── Create variants if provided ──
    const createdVariants = [];
    if (body.variants && body.variants.length > 0) {
      const discountRulesForVariants = await prisma.discountRule.findMany();

      for (const v of body.variants) {
        if (!v.colorCode) continue;

        // Auto-generate SKU for this variant
        const variantSku = generateSKU({
          category: body.category,
          brand: body.brand,
          modelNo: body.modelNo || "",
          frameSize: v.frameSize || "",
          colorCode: v.colorCode,
        });

        // Calculate discounted price for variant
        const variantMrp = v.mrp || body.mrp || 0;
        const rule = discountRulesForVariants.find(
          (r) => r.category.toUpperCase() === body.category.toUpperCase()
        );
        const variantDiscountedPrice = rule
          ? Math.round(variantMrp * (1 - rule.discountPercentage / 100))
          : variantMrp;

        const variant = await prisma.productVariant.create({
          data: {
            productId: product.id,
            colorCode: v.colorCode,
            colorName: v.colorName || null,
            frameColor: v.frameColor || null,
            templeColor: v.templeColor || null,
            frameSize: v.frameSize || null,
            bridge: v.bridge || null,
            templeLength: v.templeLength || null,
            weight: v.weight || null,
            lensColour: v.lensColour || null,
            tint: v.tint || null,
            mrp: variantMrp,
            discountedPrice: variantDiscountedPrice,
            compareAtPrice: variantMrp,
            sku: variantSku,
            barcode: v.barcode || null,
            title: `${v.colorCode}${v.frameSize ? " / " + v.frameSize : ""}`,
            locations: {
              create: (v.locations || []).map(
                (loc: { locationId: string; quantity: number }) => ({
                  locationId: loc.locationId,
                  quantity: loc.quantity || 0,
                })
              ),
            },
          },
          include: {
            images: true,
            locations: { include: { location: true } },
          },
        });

        createdVariants.push(variant);
      }
    }

    if (body.status === "PUBLISHED") {
      const shopifyResult = await createProduct({
        title: autoGeneratedData.title,
        description: body.description,
        images: body.images?.map((img) => ({
          src: img.url,
          alt: img.alt,
        })),
        seoTitle: autoGeneratedData.seoTitle,
        seoDescription: autoGeneratedData.seoDescription,
        tags: autoGeneratedData.tags.split(", "),
        productType: body.category || "",
      });

      if (shopifyResult.success && (shopifyResult as any).shopifyId) {
        await prisma.product.update({
          where: { id: product.id },
          data: { shopifyProductId: (shopifyResult as any).shopifyId },
        });

        await prisma.syncLog.create({
          data: {
            productId: product.id,
            action: "CREATE",
            status: "SUCCESS",
            message: "Synced to Shopify",
          },
        });
      } else {
        await prisma.syncLog.create({
          data: {
            productId: product.id,
            action: "CREATE",
            status: "FAILED",
            message: shopifyResult.message,
          },
        });
      }
    }

    // Log activity
    logActivity({
      userId: (auth.session?.user as any)?.id,
      userName: auth.session?.user?.name,
      userEmail: auth.session?.user?.email,
      action: "CREATE",
      entity: "PRODUCT",
      entityId: product.id,
      details: `Created product: ${autoGeneratedData.title} (${autoGeneratedData.sku})`,
    });

    return NextResponse.json(
      {
        success: true,
        data: {
          ...product,
          variants: createdVariants,
        },
        autoGenerated: autoGeneratedData,
      },
      { status: 201 }
    );
  } catch (error) {
    const errorMessage =
      error instanceof Error ? error.message : "Unknown error";
    return NextResponse.json(
      { success: false, error: errorMessage },
      { status: 500 }
    );
  }
}
